build.xml, pom.xml, src/main/java/com/coveros/selenified/selenium/Action.java, src/test/java/integration/ActionSwitchIT.java
Adding functionality to close the current window, instead of a tab
=> Issue #5: Close Window

README.md
Pull in POM to allow for deploying to maven central
=> Maven Central

pom.xml, src/main/java/com/coveros/selenified/output/Assert.java, src/main/java/com/coveros/selenified/output/LocatorAssert.java, src/test/java/integration/AssertIT.java
=> Adding direct checks for cell values

index.html, src/main/java/com/coveros/selenified/selenium/Action.java, src/main/java/com/coveros/selenified/tools/CustomHtmlUnitDriver.java, src/main/java/com/coveros/selenified/tools/General.java, src/main/java/com/coveros/selenified/tools/TestSetup.java, src/test/java/integration/ActionDoIT.java, src/test/java/integration/ActionGetIT.java, src/test/java/integration/ActionGoIT.java, src/test/java/integration/ActionIsIT.java, src/test/java/integration/ActionSwitchIT.java, src/test/java/integration/ActionWaitIT.java, src/test/java/integration/AssertIT.java, src/test/java/integration/NoBrowserIT.java, src/test/java/integration/NoLoadIT.java, src/test/java/integration/SampleTests.java, src/test/java/unit/ElementTest.java, src/test/java/unit/ExceptionTest.java, src/test/java/unit/GeneralTest.java, src/test/java/unit/SeleniumTest.java, src/test/java/unit/TestBaseTest.java, src/test/java/unit/TestSetupTest.java
Additional tests to increase coverage
=> Adding unit and integration tests

pom.xml
=> Building with older 6.9.9 testing jar

pom.xml
Added properties for dependency versions
Added properties for plugin versions
Added some more helpful properties
Defined minimum Maven version
Added a few plugins for security and compatibility checking
=> pom file improvements

pom.xml, src/main/java/com/coveros/selenified/utilities/TestSetup.java
Adds dependency for PhantomJSDriver and sets up driver when using PHANTOMJS.
=> Fix for Issue #63

README.md
Fixed the readme file per issue #56
=> corrected the typo in readme and updated the google search test

src/main/java/com/coveros/selenified/OutputFile.java, src/main/java/com/coveros/selenified/Selenified.java, src/main/java/com/coveros/selenified/application/App.java, src/main/java/com/coveros/selenified/application/Get.java, src/main/java/com/coveros/selenified/application/Is.java, src/main/java/com/coveros/selenified/application/WaitFor.java, src/main/java/com/coveros/selenified/element/Element.java, src/main/java/com/coveros/selenified/element/Get.java, src/main/java/com/coveros/selenified/element/Is.java, src/main/java/com/coveros/selenified/element/WaitFor.java, src/main/java/com/coveros/selenified/services/Call.java, src/main/java/com/coveros/selenified/utilities/CustomHtmlUnitDriver.java
Fixing levels of logs reported to main screen; Fixing html logs; fixing augmentor warnings
Will close #58
=> Fix Log Levels

README.md, pom.xml, src/main/java/com/coveros/selenified/Selenified.java, src/main/java/com/coveros/selenified/application/App.java, src/main/java/com/coveros/selenified/utilities/TestSetup.java, src/test/java/integration/ActionGoIT.java, src/test/java/unit/TestSetupTest.java
=> Ability to set screensize from cmd for all browsers

Jenkinsfile, pom.xml
adding in SQ notifications, and setting up for git hook
=> Adding credentials for auto sonar analysis

src/test/java/integration/ActionDoIT.java
=> Quick fix for blur functionality

README.md, src/main/java/com/coveros/selenified/Selenified.java, src/main/java/com/coveros/selenified/element/Element.java, src/test/java/sample/ReadmeSampleIT.java
Per some requests from Byron, updates were made to readme #116 #117 #118 #119
=> Updates to Readme

src/main/java/com/coveros/selenified/element/Assert.java, src/main/java/com/coveros/selenified/element/Element.java, src/main/java/com/coveros/selenified/element/Equals.java, src/main/java/com/coveros/selenified/element/Matches.java, src/test/java/integration/AssertMatchesIT.java
Addresses #84 
Added a new class for assertion on regexes, and a bundle of ITs
=> Adding new Matches assertion

src/main/java/com/coveros/selenified/OutputFile.java, src/main/java/com/coveros/selenified/element/Element.java, src/main/java/com/coveros/selenified/element/Equals.java, src/main/java/com/coveros/selenified/element/Get.java, src/main/java/com/coveros/selenified/element/Matches.java, src/main/java/com/coveros/selenified/element/State.java, src/main/java/com/coveros/selenified/element/WaitFor.java, src/test/java/integration/ActionGetIT.java
Instead of returning WebElements, we should be returning Selenified Elements on table commands.
This realigns that problem
This is a non-backwards compatible change for those previously using these methods, and will push the release to 3.1.0
=> Modifying Table Structure

pom.xml, src/main/java/com/coveros/selenified/Capabilities.java, src/test/java/unit/CapabilitiesTest.java
Updated to new method calls where needed
=> Bump Versions

Jenkinsfile, src/main/java/com/coveros/selenified/OutputFile.java, src/main/java/com/coveros/selenified/Selenified.java, src/main/java/com/coveros/selenified/application/App.java, src/main/java/com/coveros/selenified/application/WaitFor.java, src/main/java/com/coveros/selenified/element/Element.java, src/main/java/com/coveros/selenified/element/WaitFor.java, src/main/java/com/coveros/selenified/services/Call.java, src/main/java/com/coveros/selenified/utilities/Listener.java, src/test/java/integration/ActionDoIT.java, src/test/java/integration/ActionSwitchIT.java, src/test/java/unit/OutputFileTest.java
We have superfluous and confusing Success and Result entries, cleaning that up
Found a few missing tests, adding them in
=> Cleaning up Tests

src/main/java/com/coveros/selenified/element/Equals.java, src/test/java/integration/AssertEqualsIT.java
=> Assert Match

Jenkinsfile, README.md, pom.xml, src/main/java/com/coveros/selenified/Capabilities.java, src/main/java/com/coveros/selenified/Selenified.java, src/main/java/com/coveros/selenified/application/App.java, src/main/java/com/coveros/selenified/exceptions/InvalidBrowserOptionsException.java, src/main/java/com/coveros/selenified/exceptions/InvalidHubException.java, src/main/java/com/coveros/selenified/exceptions/InvalidProxyException.java, src/main/java/com/coveros/selenified/exceptions/InvalidSauceException.java, src/main/java/com/coveros/selenified/services/HTTP.java, src/main/java/com/coveros/selenified/utilities/Listener.java, src/main/java/com/coveros/selenified/utilities/Property.java, src/main/java/com/coveros/selenified/utilities/Reporter.java, src/main/java/com/coveros/selenified/utilities/Sauce.java, src/test/java/integration/ActionDoIT.java, src/test/java/integration/ServicesErrorIT.java, src/test/java/sample/ReadmeSampleIT.java, src/test/java/unit/AppTest.java, src/test/java/unit/CallTest.java, src/test/java/unit/CapabilitiesTest.java, src/test/java/unit/ExceptionTest.java, src/test/java/unit/PropertyTest.java, src/test/java/unit/ReporterTest.java, src/test/java/unit/ResponseTest.java, src/test/java/unit/SauceTest.java, src/test/java/unit/SaveProperties.java, src/test/resources/selenified.properties
Updating how proxy is handled and parsed in, and adding test for proxy into the pipeline
Addresses #171
=> Proxy Support

src/main/java/com/coveros/selenified/application/WaitFor.java, src/main/java/com/coveros/selenified/element/check/wait/WaitForEquals.java, src/main/java/com/coveros/selenified/element/check/wait/WaitForState.java, src/main/java/com/coveros/selenified/utilities/Property.java, src/test/java/unit/PropertyTest.java, src/test/java/unit/SaveProperties.java, src/test/resources/selenified.properties
=> Moving default wait time being hardcoded in code to properties file

src/main/java/com/coveros/selenified/element/Element.java, src/test/java/integration/ActionGetIT.java, src/test/java/integration/ElementIT.java
partially addresses #152 
Fixes how elements are being handled without matches
=> Cleaning up bad matchers

src/main/java/com/coveros/selenified/element/Element.java, src/main/java/com/coveros/selenified/utilities/Constants.java, src/main/java/com/coveros/selenified/utilities/Listener.java, src/test/java/unit/ListenerTest.java
=> Skip Tests Not in Report

Jenkinsfile, src/main/java/com/coveros/selenified/Browser.java
Modifying Jenkinsfile to archive off pretty reports for easier reading/reviewing
Also adding small block of code to verify all browsers can successfully run - needs to be expanded on for #103 
Added alias for InternetExplorer as IE for simplicity
=> Jenkinsfile Updates

Jenkinsfile, public/index.html, src/main/java/com/coveros/selenified/application/App.java, src/main/java/com/coveros/selenified/application/WaitFor.java, src/main/java/com/coveros/selenified/element/check/Check.java, src/main/java/com/coveros/selenified/element/check/wait/WaitForEquals.java, src/main/java/com/coveros/selenified/element/check/wait/WaitForState.java, src/main/java/com/coveros/selenified/services/Response.java, src/main/java/com/coveros/selenified/utilities/Constants.java, src/main/java/com/coveros/selenified/utilities/Property.java, src/test/java/integration/WaitForEqualsIT.java, src/test/java/integration/WaitForIT.java, src/test/java/integration/WaitForStateIT.java, src/test/java/unit/PropertyTest.java, src/test/java/unit/SaveProperties.java, src/test/resources/selenified.properties
=> Transforming old waits to fluent waits

src/main/java/com/coveros/selenified/Browser.java, src/test/java/unit/BrowserTest.java
=> Adding in extra browser details

src/main/java/com/coveros/selenified/Browser.java, src/test/java/unit/BrowserTest.java
=> Adding in clarity for API tests

src/main/java/com/coveros/selenified/Selenified.java, src/main/java/com/coveros/selenified/utilities/Listener.java, src/main/java/com/coveros/selenified/utilities/ReportOverview.java
=> Adding details to overall report with failure reason and stack trace

Jenkinsfile
Cleaning up what/how files are archived/saved off
=> Archiving Files

src/main/java/com/coveros/selenified/utilities/Property.java, src/test/java/unit/PropertyTest.java, src/test/java/unit/SaveProperties.java
Making updates per #208 request
=> Setting selenified.properties to relative resource path

Jenkinsfile, src/main/java/com/coveros/selenified/Selenified.java, src/test/java/integration/ServicesErrorIT.java, src/test/java/integration/hub/LambdaTestIT.java, src/test/java/integration/hub/SauceIT.java
Addressing issue #219 and simplifying values stored/saved off in Selenified
=> Threaded Name

src/main/java/com/coveros/selenified/Capabilities.java
=> Reducing selenium logging
